Add run_all_tests function
This commit adds function to run all
tests and report results at the end.

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

diff --git a/test/run b/test/run
--- a/test/run
+++ b/test/run
@@ -14,6 +14,16 @@ image_dir=$(readlink -zf ${test_dir}/..)
 
 . "$test_dir/test-lib.sh"
 
+test_short_summary=''
+TESTSUITE_RESULT=0
+
+TEST_LIST="\
+test_s2i_usage
+test_docker_run_usage
+test_application
+test_application_with_user
+"
+
 # TODO: This should be part of the image metadata
 test_port=8080
 
@@ -74,15 +84,23 @@ cleanup() {
     docker rmi -f ${IMAGE_NAME}-testapp
   fi
   rm -rf ${test_dir}/test-app/.git
+
+  echo "$test_short_summary"
+
+  if [ $TESTSUITE_RESULT -eq 0 ] ; then
+    echo "Tests for ${IMAGE_NAME} succeeded."
+  else
+    echo "Tests for ${IMAGE_NAME} failed."
+  fi
+  exit $TESTSUITE_RESULT
 }
 
 check_result() {
   local result="$1"
   if [[ "$result" != "0" ]]; then
-    info "TEST FAILED (${result})"
-    cleanup
-    exit $result
+    TESTCASE_RESULT=1
   fi
+  return $result
 }
 
 wait_for_cid() {
@@ -172,6 +190,11 @@ test_application() {
   cleanup_test_app
 }
 
+test_application_with_user() {
+  # Test application with random uid
+  CONTAINER_ARGS="--user 12345" test_application
+  check_result $?
+}
 cid_file=$(mktemp -u --suffix=.cid)
 
 # Since we built the candidate image locally, we don't want S2I attempt to pull
@@ -182,19 +205,28 @@ prepare
 run_s2i_build
 check_result $?
 
-# Verify the 'usage' script is working properly when running the base image with 's2i usage ...'
-test_s2i_usage
-check_result $?
+function run_all_tests() {
+  for test_case in $TEST_SET; do
+    info "Running test $test_case ... "
+    TESTCASE_RESULT=0
+    $test_case
+    local test_msg
+    if [ $TESTCASE_RESULT -eq 0 ]; then
+      test_msg="[PASSED]"
+    else
+      test_msg="[FAILED]"
+      TESTSUITE_RESULT=1
+    fi
+    printf -v test_short_summary "%s %s for %s\n" "${test_short_summary}" "${test_msg}" "$test_case"
+    [ -n "${FAIL_QUICKLY:-}" ] && {
+      cleanup
+      return 1
+    }
+  done;
+}
 
-# Verify the 'usage' script is working properly when running the base image with 'docker run ...'
-test_docker_run_usage
-check_result $?
+TEST_SET=${TESTS:-$TEST_LIST} run_all_tests
 
-# Test application with default uid
-test_application
-
-# Test application with random uid
-CONTAINER_ARGS="--user 12345" test_application
 cleanup
 
 info "All tests finished successfully."
