check whether varnish.params is present
Signed-off-by: Tomas Tomecek <ttomecek@redhat.com>

diff --git a/s2i/bin/assemble b/s2i/bin/assemble
--- a/s2i/bin/assemble
+++ b/s2i/bin/assemble
@@ -10,6 +10,10 @@ if [ ! -f "${VARNISH_CONFIGURATION_PATH}/default.vcl" ]; then
     echo "Error: The varnish configuration must contain 'default.vcl' file."
     exit 1
 fi
+if [ ! -f "${VARNISH_CONFIGURATION_PATH}/varnish.params" ]; then
+    echo "Error: The varnish configuration must contain 'varnish.params' file."
+    exit 1
+fi
 
 cat "${VARNISH_CONFIGURATION_PATH}/default.vcl"
 
